/*import React, { Component,Image,View ,Text} from 'react'
import styles from './Styles' */

import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import * as FileSystem from  'react-native-fs'

import React, { Component ,useEffect,useState} from 'react'
import {Image, StyleSheet, View, Alert ,Text,Dimensions,Pressable,  TextInput,ImageBackground,SafeAreaView,StatusBar,TouchableOpacity,ActivityIndicator,BackHandler,TouchableHighlight} from 'react-native'
//import { TouchableOpacity } from 'react-native-gesture-handler';
import Modal from "react-native-modal";
import animLoading from '../animations/loading.json'
import Tags from "react-native-tags";
import Lottie from 'lottie-react-native';





const windowWidth = wp('90%')
let windowHeight = hp('70%');


import {LogBox} from "react-native";
import { useRoute } from '@react-navigation/native';

LogBox.ignoreLogs([
"exported from 'deprecated-react-native-prop-types'.",
])


import { showMessage, hideMessage } from "react-native-flash-message";


import { ScrollView } from 'react-native-gesture-handler';
import { Button } from '@react-native-material/core';


export default  function TemplatePreview(props){
  const route = useRoute();
  const [sizeImgDone, setsizeimgDone] = useState(false);
  const [isloading,setloading] = useState(true)
  const [Imgheight, setimgHeight] = useState(100);
  const [Imgwidth,setimgWidth] = useState(100);
  const [keys,setkeys] = useState([])
  const [selectedKey,setselectedKey]=useState('')
  const [listKeys,setListKeys]=useState([])


 

  //console.log("item : ",Object.keys(props.nav))  
 
      const Note = ()=>{
          return(
            <View style={{ backgroundColor:'white' , height:hp('4%'),width:wp('90%'),justifyContent:'center',justifyContent:'space-evenly',borderBottomColor:'gray',borderBottomWidth:0.5}}>
            {/* <IconNote name="md-alert-circle-outline" size={20} color='black' style={{marginRight:0}}></IconNote> */}
  
              <Text style={{fontWeight:'bold',color:'black',marginLeft:10}} >Key Details : </Text>
            </View>
          )
        
       }
       const MyTagInput = () => (
        <Tags
          //initialText="monkey"
          // textInputProps={{
          //   placeholder: "Any type of animal"
          // }}
          initialTags={listKeys}
          maxNumberOfTags={listKeys.length}
        //  onChangeTags={tags => console.log(tags)}
          onTagPress={(index, tagLabel, event, deleted) =>
           { console.log(index, tagLabel);
            setselectedKey(tagLabel)}
          }
          containerStyle={{ justifyContent: "center" }}
        //  inputStyle={{ backgroundColor: "white" }}
        readonly={true}
          renderTag={({ tag, index, onPress, deleteTagOnPress, readonly }) => (
            <TouchableOpacity key={`${tag}-${index}`} onPress={onPress}>
              <View style={{backgroundColor:'white',borderRadius:15,marginRight:20,marginBottom:7,marginTop:10,marginLeft:5,
              padding:5,
            elevation:5,
            shadowColor:'black',
          }}>

              <Text style={{fontWeight:'900',color:'black'}} >{tag}</Text>
              </View>
            </TouchableOpacity>
          )}
        />
      );

  
 // console.log('img ',img)
 
  useEffect(()=>{
    const img = props.props.imguri64
    Image.getSize(img, (width, height) => {

        setimgWidth(width)
        setimgHeight(height)
       
       
       // setloading(false)
       })
  },[props.props])

  useEffect(()=>{
    const templateName = props.props.NameofTemplate

    fetch(`http://backend.docscanner.teambros.co.in/cropper/get-by-template-name/${templateName}`)
        .then((res)=>res.json())
        .then((jres)=>{
          
          setkeys(jres.det)

          const listKeys  = []
          for(var item in jres.det){
            listKeys.push(jres.det[item].key)
           // console.log(item)



          }
         // console.log(listKeys)
          setListKeys(listKeys)
         // console.log(jres.det)
          //console.log(templateName,keys)
          
          var path = FileSystem.ExternalDirectoryPath + `/myscandata.json`;
          FileSystem.writeFile(path, JSON.stringify({"scandata":[]}), 'utf8')
          .then((success) => {
            console.log('empty json file created');
            // setModalVisible(false);
            // propss.props.navigate('Camera',{tempName:item["NameofTemplate"],img_temp:item["imguri64"],filename:fname,keydata:jres.det,scan:1})
          })
          .catch((err) => {
            console.log(err);
          });
          
          setloading(false)   
       
        })
        
        .catch((err)=>{
          console.log(err);
          props.func()
         
          showMessage({
            message: "003 Network problem-",
            description: `Please Check Your Internet Connection`,
            type: 'danger',
            hideStatusBar:true,
            duration:2200
          });
         
        })
    

     
       
  },[props.props])


   // console.log(Imgwidth, Imgheight)

    

        const v_scale = windowHeight/Imgheight
        const h_scale =windowWidth/Imgwidth
      
        const x = (v_scale<h_scale)?v_scale:h_scale;
      
       // console.log(x,v_scale,h_scale)
      
       const  Svgheight = (Imgheight*x).toString()+"px"
       const  Svgwidth = (Imgwidth*x).toString()+"px"
      
       const rem_height =windowHeight-(Imgheight*x)
       const imgdown_hight = (rem_height<=((windowHeight/100)*15))?rem_height:((rem_height/100)*75)
       const imgup_hight =rem_height - imgdown_hight
      
      // console.log("up  dow : ",imgup_hight,imgdown_hight)

    if(isloading){

      return(
        <>
          
        <View style={styles.load}>
          <View style={{flex:1}}>
                  <View style={{justifyContent:"center",alignItems:'center'}}>
           <Lottie source={animLoading} autoPlay loop resizeMode="contain"  style={{height:hp('10%'),width:wp('10%')}}/>
           </View>
           </View>
        
        {/* <Text style={{color:'black'}}> Getting ready ..</Text> */}
        </View>
        </>

    
    )
    }

    else{


    return(
      

      <View style={{justifyContent:"center",alignItems:'center',backgroundColor:'rgba(255, 254, 255, 0)',height:hp('90%')}}>
        <View style={styles.container}>
      
      <View //style={{height:imgup_hight}}
      >

      </View>
      
        <View style={{justifyContent:"center",alignItems:'center'}}>
          <View style={{height:Imgheight*x,width:Imgwidth*x,backgroundColor:'green'}}>
            <ImageBackground source={{uri:props.props.imguri64}} style={{width: '100%', height: '100%',backgroundColor:'black',resizeMode:'contain'}}>
            {
              keys.map((item)=>{
                return(
                     
                     <View key={item["_id"]}>
                      {/* <Pressable onPress={() =>{
                                        console.log("clicked")
                                        console.log(item['coordinates']['w']*(Imgwidth*x))
                                        
                                        setModalVisible(true);setitemOcr(item);setn_text(item["OCRResp"])
                                      }} key={item["_id"]}> */}

          <View style={styles.box({x:(item['coordinates']['x']*(Imgwidth*x)),y:(item['coordinates']['y']*(Imgheight*x)),w:item['coordinates']['w']*(Imgwidth*x),h:item['coordinates']['h']*(Imgheight*x),key:item.key,selectedKey:selectedKey
        
        })} >
          <View style={{justifyContent:'center',alignItems:'center'}}>
          <ScrollView horizontal={true} >
          <Text style={{color:'black',alignSelf:'center',fontSize:(item['coordinates']['h']*(Imgwidth*x))}}>
            {item["OCRResp"]}
          </Text>
          </ScrollView>
          </View>
                        
                        </View>
                     </View>

                 
            
                )
              })
       }

            </ImageBackground>
          </View>
                

             <View style={{height:imgdown_hight,backgroundColor:'white',height:hp('26%'),width:wp('90%'),alignItems:'center',
            }}>
              <Note></Note>
             
                
             <View style={{height:hp('16%'),borderBottomColor:'gray',borderBottomWidth:0.5,width:wp('90%')}}>
               <ScrollView>
                 <MyTagInput>
                
                </MyTagInput>
                </ScrollView>
             </View>

              
              <View stype={{marginBottom:0,backgroundColor:'red',}}>
      <Button  title="proceed" margin={5} onPress={async()=>{
        // console.log('lkk')
       
           //

           const myFirstPromise = new Promise((resolve, reject) => {
            props.func()

           
            setTimeout(() => {


              resolve("foo");
            }, 600);

              // Yay! Everything went well!
          });

          myFirstPromise.then((successMessage) => {
            // successMessage is whatever we passed in the resolve(...) function above.
            // It doesn't have to be a string, but if it is only a succeed message, it probably will be.
            console.log(`Yay! ${successMessage}`);
            props.nav.navigate('Camera',{tempName:props.props["NameofTemplate"],img_temp:props.props["imguri64"],filename:'kj',keydata:keys,backButton:false})

           
          });

  

        }} color={'#7FBCD2'} />

                 </View>
            
              </View>
              
    
      </View>
            </View>
            
      </View>
     

      
   

  )
    }

}

const styles = StyleSheet.create({
  box:({x,y,w,h,key,selectedKey})=>{
    var bordercolor = '#543629'
    var borwidth=0.5
    if(key==selectedKey){
      bordercolor='green'
      borwidth=3

    }
    return{
      position:'absolute',
      top:y,
      left:x,
    
      width:w,
      height:h,
      borderWidth:borwidth,
      borderColor:bordercolor,
     
      //zIndex:300,
     // backgroundColor:'white',
    //  borderRadius: 10,
    
      
      


    } 

     
  },
  container: {
    
     justifyContent:'center',
    alignItems:'center',
    
    backgroundColor:'rgba(255, 254, 255, 0)',
    blurRadius:'1',
    height:hp('90%'),
    width:wp('90%'),
    marginBottom:hp('1%')
    

    
  },
  img:{
    //flex:0.9,
   // backgroundColor:'green',
    
  },
  btn:{
    width:wp('100%'),
   alignSelf:'center',
   flexDirection:'row',
  // backgroundColor:'yellow',
  // marginTop:hp('8%'),
   justifyContent:'space-evenly',
   marginBottom:10
  
  },
  centeredView: {
   // flex: 1,
    //justifyContent: "center",
    alignItems: "center",
   // marginTop: 22,
   backgroundColor:'green',
  // height:hp('50%')
    
    
  },
  modalView: {
    // alignItems:'baseline',
    // margin: 20,
    // backgroundColor: "white",
    // borderRadius: 20,
    // padding: 35,
    // alignItems: "center",
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 2
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 4,
    // elevation: 5
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    //color:'#5364b2'
  },
  buttonOpen: {
    backgroundColor: "#7FBCD2",
  },
  buttonClose: {
    backgroundColor: "#7FBCD2",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center"
  },
  modalText: {
   //marginBottom:3 ,
    textAlign: "center",
    color:'black',
    marginTop:20
  },
  textInput: {
    justifyContent: "center",
    alignItems: "stretch",
    height: 40,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "black",
    //backgroundColor:'red',
    borderRadius:10

  }
  ,
  load:{
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection:'row',
    //backgroundColor:'red'

  }
})
//<Image source={require(route.params.path)} /> <Image source={require('./Default.jpg')} />

//<Image source={{uri:'file:///storage/emulated/0/DCIM/Restored/IMG20220316134958.jpg', width: 100,  height: 100}} />

const data1 = [
  {
          "coordinates": {
          "x": 0.19974044940438687,
          "y": 0.28295283334065474,
          "w": 0.09874308713570168,
          "h": 0.04388039664826179
          },
          "_id": "62b33c825d13528bd83debdf",
          "templateName": "VIT MID-1",
          "key": "Subject",
          "regex": "string",
          "__v": 0
  },
  {
  "coordinates": {
  "x": 0.516121332546533,
  "y": 0.22696754429167118,
  "w": 0.3748205861737651,
  "h": 0.03934101249932418
  },
  "_id": "62b33cb55d13528bd83debe1",
  "templateName": "VIT MID-1",
  "key": "Reg N",
  "regex": "string",
  "__v": 0
  },
  {
  "coordinates": {
  "x": 0.516121332546533,
  "y": 0.28749219109030333,
  "w": 0.37885094567927347,
  "h": 0.03177545144896194
  },
  "_id": "62b33ce05d13528bd83debe3",
  "templateName": "VIT MID-1",
  "key": "Date",
  "regex": "string",
  "__v": 0
  },
  {
  "coordinates": {
  "x": 0.7418197420884937,
  "y": 0.17854777669411628,
  "w": 0.10680378856746832,
  "h": 0.027236093699313364
  },
  "_id": "62b33d035d13528bd83debe5",
  "templateName": "VIT MID-1",
  "key": "Branch",
  "regex": "string",
  "__v": 0

  },
  {
  "coordinates": {
  "x": 0.19369496288387456,
  "y": 0.22242816014273356,
  "w": 0.22569844470046083,
  "h": 0.05901157154756434
  },
  "_id": "62b33db45d13528bd83debe8",
  "templateName": "VIT MID-1",
  "key": "Name",
  "regex": "string",
  "__v": 0
  }
  ]

  
const ddd =[ { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
   Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
  Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' },
  { Name: 'B.pradup Kumar',
    Q1Q2best: '8',
    Q1a: 'S',
    Q1b: '-',
    Q1total: '8',
    Q2a: '-',
    Q2b: '-',
    Q2total: '-',
    Q3Q4best: '9',
    Q3a: '9',
    Q3b: '-',
    Q3total: 'a',
    Q4a: '-',
    Q4b: '-',
    Q4total: '-',
    Q5Q6best: '8',
    Q5a: '8',
    Q5b: '-',
    Q5total: '8',
    Q6a: '-',
    Q6b: '-',
    Q6total: '-',
    RegNo: '19PAIA0308',
    Subject: 'that Transfer',
    TotalMarks: '25',
    'TotalMarks(20)': '17' } ]
